### ISSUE TITLE
Error Exception

### ISSUE THREAD

**Issue by ismailaya** [dbrax/pesapal-laravel#1]
I got this error when processing request => Undefined array key "scheme"

**Comment by dbrax** [comment]
Hellow @ismailaya 

Please share your full request 
    also what do you pass as the URL or endpoint config('pesapal.api_url') 

Also please don't share your pesapal secret or key

**Comment by ismailaya** [comment]
I fixed it

**Comment by dbrax** [comment]
Thanks great.

Happy coding 👍🏿

**Comment by ismailaya** [comment]
Thanks!
